# Generated by Django 4.1.10 on 2023-07-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cisco_support', '0007_alter_ciscodevicetypesupport_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciscosupport',
            name='contract_site_address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ciscosupport',
            name='contract_site_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ciscosupport',
            name='contract_site_country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ciscosupport',
            name='contract_site_customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ciscosupport',
            name='contract_site_state_province',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ciscosupport',
            name='service_contract_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ciscosupport',
            name='service_line_description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ciscosupport',
            name='warranty_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
